name: Coinbox Test
run-name: ${{github.actor}} is running tests
on: push
defaults:
    run:
        shell: bash
        working-directory: ./src
jobs:
    Run-All-Tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "Installing dependencies"
            - run: python -m pip install -r ../requirements.txt
            - run: echo "Running tests"
            - run: coverage run -m unittest
            - run: coverage html -d coverage_html